In [2]:
import numpy as mp
import pandas as pd

Series is 1D and DataFrames are 2D objects
But why?
And what exactly is index?

In [3]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a # both index are interdepent

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [8]:
#1.pd.multiIndex.from_tuple()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.MultiIndex.from_tuples(index_val)# 1st option
a.levels[0]# cse,ece
a.levels[1]# year

Index([2019, 2020, 2021, 2022], dtype='int64')

In [9]:
#2.pd.multiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [12]:
#for creating series
s = pd.Series([1,2,3,4,5,6,7,8],index=pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]]))
s# it is is a 2D series

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [13]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [17]:
#unstack:remove col move to rows
temp=s.unstack()#convert a multi index series into df

In [18]:
#stack : rows-> col
temp.stack()#convert a df into multi index series

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [23]:
#multi index is use to convert nth dim datframes info to dataframe(2D) or series(1D)
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.MultiIndex.from_tuples(index_val)
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = a,#multi index
    columns = ['avg_package','students']
)
branch_df1
#in this we heiarchy in row

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [24]:
branch_df1.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [25]:
branch_df1['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [26]:
# Now heiarchy in col
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [29]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [28]:
# Multiindex df in terms of both cols and index
#4D
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = a,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

STACKING  AND UNSTACKING

In [34]:
branch_df1.unstack().stack()

/tmp/ipykernel_526/1991893145.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

WORKING WITH MULTIINDEXING

In [37]:
branch_df3.head(2)
branch_df3.shape
branch_df3.index
branch_df3.columns

MultiIndex([( 'delhi', 'avg_package'),
            ( 'delhi',    'students'),
            ('mumbai', 'avg_package'),
            ('mumbai',    'students')],
           )

In [38]:
#extracting rows single
branch_df3.loc[('cse',2019)]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: (cse, 2019), dtype: int64

In [40]:
#multi row
branch_df3.loc[('cse',2019):('ece',2020):2]#alternate

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [42]:
#Extracting cols
#single
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [44]:
#Extracting both
print(branch_df3.loc[('cse',2019),('delhi','students')])

2

In [45]:
# sort index
# both -> descending -> diff order
# based on one level
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=0,ascending=[False])

               delhi               mumbai
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [46]:
# multiindex dataframe(col) -> transpose
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [47]:
#swaplevel
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

Long Vs Wide Data
Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes.

Long format is where, for each data point we have as many rows as the number of attributes and each row contains the value of a particular attribute for a given data point.

In [51]:
#melt -> simple example branch
#wide to long
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [52]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech            50

In [54]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

In [55]:
# melt -> real world example
death = pd.read_csv('/content/time_series_covid19_deaths_global.csv')
confirm = pd.read_csv('/content/time_series_covid19_confirmed_global.csv')

In [60]:
death.head()# wide fromat

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [58]:
confirm.head().shape#wide

(5, 1081)

In [63]:
#country->date->confirm->death
death_long = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='death')
death_long.head()

  Province/State Country/Region       Lat       Long     date  death
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
1            NaN        Albania  41.15330  20.168300  1/22/20      0
2            NaN        Algeria  28.03390   1.659600  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0
4            NaN         Angola -11.20270  17.873900  1/22/20      0

In [64]:
confirm_long = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='confirm')
confirm_long.head()

  Province/State Country/Region       Lat       Long     date  confirm
0            NaN    Afghanistan  33.93911  67.709953  1/22/20        0
1            NaN        Albania  41.15330  20.168300  1/22/20        0
2            NaN        Algeria  28.03390   1.659600  1/22/20        0
3            NaN        Andorra  42.50630   1.521800  1/22/20        0
4            NaN         Angola -11.20270  17.873900  1/22/20        0

In [65]:
confirm_long.merge(death_long,on=['Province/State','Country/Region','Lat','Long','date']).head()

  Province/State Country/Region       Lat       Long     date  confirm  death
0            NaN    Afghanistan  33.93911  67.709953  1/22/20        0      0
1            NaN        Albania  41.15330  20.168300  1/22/20        0      0
2            NaN        Algeria  28.03390   1.659600  1/22/20        0      0
3            NaN        Andorra  42.50630   1.521800  1/22/20        0      0
4            NaN         Angola -11.20270  17.873900  1/22/20        0      0